Post CRUD Feature
ryoheiw/twitter-clone pull request #2
Opened 2021-02-17 03:56 UTC by ryoheiw

Create, Read, Update, Delete on Posts.

I have also done testing, documentation, and specs for each function.

2021-02-17 05:29 UTC, shunjilin requested changes
Looks good overall, especially the comments are very detailed and helpful!

Some suggestions for the changes
- Try to limit the surface area of your public functions - only define public functions that are needed and accessed outside of the module -> if it is used internally, just define them as private functions. You may need to remove the doc / spec / tests on them.

- Formatting!
- Some style guides specific to our codebase

2021-02-17 05:29 UTC, shunjilin commented on src/lib/twitter/tweets.ex
> +  @spec get_post(integer()) :: Twitter.Tweets.Post.t() | nil
If this is used only within the module, make it a private function!

2021-02-17 05:29 UTC, shunjilin commented on src/lib/twitter/tweets.ex
> +    Repo.all(
This is perfectly fine, but as a style guide to keep consistency within Restar we try to use the pipe syntax exclusively, see if you can rewrite this in that style! e.g. `Post |> where() |> preload() |> Repo.all()`

2021-02-17 05:29 UTC, shunjilin commented on src/lib/twitter/tweets.ex
> +  def delete_tweet(id) do
can use pipe syntax here,
```elixir
id
|> get_post()
|> Repo.delete()
```

2021-02-17 05:29 UTC, shunjilin commented on src/lib/twitter_web/controllers/post_controller.ex
> +    IO.inspect(params)
remove debugging code

2021-02-17 05:29 UTC, shunjilin commented on src/lib/twitter_web/controllers/post_controller.ex
> +      # user changeset to display better error when you refactor this.
TODO?
There should be a way to automatically render changeset errors in your form, instead or redirecting, you may need to reinitialize the page with the invalid changeset

something like ` render(conn, "new.html", changeset: changeset)`
in the form you can use some kind of error_tag like: `<%= error_tag f, :password %>`
see twitterweb.errorhelpers in this repo

2021-02-17 05:29 UTC, shunjilin commented on src/lib/twitter_web/controllers/user_controller.ex
> +    # IO.inspect(user_params) === %{}
remove this

2021-02-17 05:29 UTC, shunjilin commented on src/lib/twitter_web/templates/layout/app.html.eex
> +
format your .eex files, there should be some extension to help with that

2021-02-17 05:29 UTC, shunjilin commented on src/lib/twitter_web/templates/page/index.html.eex
> +
formatting

2021-02-17 05:29 UTC, shunjilin commented on src/priv/repo/migrations/20210208074342_create_users.exs
> +      add(:username, :string)
do you want username to be nullable? just checking in case

2021-02-17 05:29 UTC, shunjilin commented on src/test/twitter/accounts_test.exs
> +      assert user.password_hash !== @valid_attrs.password
you can use refute user.password_hash == @valid_attrs.password

2021-02-17 05:29 UTC, shunjilin commented on src/test/twitter_web/controllers/page_controller_test.exs
> +
formatting!

2021-02-17 05:29 UTC, shunjilin commented on src/test/twitter_web/controllers/post_controller_test.exs
> +    test "create action successfully creates post with valid data + redirects to index", %{
try to be consistent when naming the tests, e.g. in your TweetController test I think you use "/GET successfully...", I think the /GET /POST etc naming convention is easier to understand, and is also what we use in our codebase

2021-02-17 05:47 UTC, shunjilin commented on src/lib/twitter_web/views/page_view.ex
> +    |> Enum.at(0)
you can use `hd()` here

2021-02-17 07:45 UTC, shunjilin reviewed
more comments!

2021-02-17 07:45 UTC, shunjilin commented on src/lib/twitter/tweets.ex
>      Repo.get(Post, id)
Nitpick, but just a style guide again:

```
Post
|> preload(:user) # from Ecto.Query
|> Repo.get(id)
```

preferable to preload before Repo.get to do it in the same request, Repo.preload is more for preloading from an existing struct instead of from retrieving from database:
https://hexdocs.pm/ecto/Ecto.Repo.html#c:preload/3

2021-02-17 07:45 UTC, shunjilin commented on src/lib/twitter/tweets.ex
> +    # Repo.all(
remove the comments!

2021-02-17 07:45 UTC, shunjilin commented on src/lib/twitter/tweets.ex
> +    |> Repo.preload(:user)
use Ecto.Query.preload instead of Repo.preload, and move preloading to before Repo.all

You can also do import `Ecto.Query` at the top so that you don't have to type `Ecto.Query.order_by` and `Ecto.Query.preload`, instead just `|> preload |> order_by`

2021-02-17 09:07 UTC, shunjilin commented
Looks good to me! please handover to Yokota san to check!

2021-02-17 09:33 UTC, MasashiYokota commented on src/lib/twitter/accounts.ex
> +  alias Twitter.Accounts.{User}
```suggestion
  alias Twitter.Accounts.User
```

2021-02-17 10:46 UTC, MasashiYokota requested changes
I've added nits comments

2021-02-17 10:46 UTC, MasashiYokota commented on src/test/twitter_web/controllers/page_controller_test.exs
> +    alias Twitter.Accounts
You should put the syntax for reading external modules (ex. `alias`, `use` and so on) to the top of module as far as possible.

2021-02-17 10:46 UTC, MasashiYokota commented on src/test/twitter_web/controllers/session_controller_test.exs
> +               "Login"
```suggestion
      assert html_response(conn, 200) =~ "Login"
```

2021-02-18 05:20 UTC, MasashiYokota requested changes

2021-02-18 05:20 UTC, MasashiYokota commented on src/lib/twitter/tweets.ex
> +    post
```suggestion
    id
    |> get_post()
```

2021-02-18 05:20 UTC, MasashiYokota commented on src/lib/twitter_web/controllers/post_controller.ex
> +    content = params["content"]
```suggestion
  def create(conn, %{"content" => content}) do
    current_user = conn.assigns.current_user
```
Use pattern matching

2021-02-18 05:20 UTC, MasashiYokota commented on src/lib/twitter_web/controllers/post_controller.ex
> +    case Tweets.update_tweet(params["id"], %{content: params["content"]["content"]}) do
```suggestion
  def update(conn, %{"id" => id, "content" => content}) do
    case Tweets.update_tweet(id, %{content: content}) do
```
Use pattern matching. And you shouldn't pass the parameter which nests unnecessarily.

2021-02-18 06:10 UTC, MasashiYokota commented
LGTM 👍

2021-02-18 06:13 UTC, merged