お気に入りの機能
ryoheiw/twitter-clone pull request #3
Opened 2021-02-19 08:33 UTC by ryoheiw

The central feature is like_post and unlike_post but to include this new functionality, I had to create a join table and alter some of the code such as the get_user function and authentication layer to preload the association of favorite posts. With the favorite posts of the user pre-loaded and available, I was able to create the html for like/unlike based on whether the user had  liked the post before.

2021-02-19 08:59 UTC, shunjilin requested changes
some nitpicks!

2021-02-19 08:59 UTC, shunjilin commented on src/lib/twitter_web/controllers/favorite_controller.ex
> +      {:error, %Ecto.Changeset{} = _changeset} ->
if you are not going to use the Ecto Changeset but want to match on it, you can leave out the `=_changeset` as it is quite obvious

2021-02-19 08:59 UTC, shunjilin commented on src/lib/twitter_web/controllers/favorite_controller.ex
> +      {:error, %Ecto.Changeset{} = _changeset} ->
same here, see below

2021-02-19 08:59 UTC, shunjilin commented on src/lib/twitter_web/controllers/post_controller.ex
> +  def update(conn, %{"id" => id, "content" => content} = params) do
Don't have to assign to params if you do not use it later

2021-02-19 08:59 UTC, shunjilin commented on src/lib/twitter_web/templates/page/index.html.eex
> +            <%= if Enum.any?(@current_user.favorite_posts, fn x -> x.post_id == tweet.id end) do %>
try to use more descriptive parameters rather than x, sometimes not naming may be easier to understand, using the lambda capture syntax `&(&.post_id == tweet.id)`

You may want to refactor this into a view function as it is quite involved

2021-02-19 08:59 UTC, shunjilin commented on src/test/twitter/accounts_test.exs
> +      get_user = Accounts.get_user(user.id)
usual naming convention is expected_user and actual_user

2021-02-19 08:59 UTC, shunjilin commented on src/lib/twitter/accounts.ex
> +      |> preload(:favorite_posts)
is it necessary to preload here as well as in the auth? I may be wrong but would be great if there is just one place to preload the necessary fields

2021-02-19 08:59 UTC, shunjilin commented on src/test/twitter_web/controllers/favorite_controller_test.exs
> +end
may want to check if non-signed in user is blocked from accessing

2021-02-19 09:09 UTC, MasashiYokota commented on src/lib/twitter/accounts.ex
> +    |> Repo.preload(:favorite_posts)
```suggestion
    User
   |> preload(:favorite_posts)
    |> Repo.get(id)
```

2021-02-19 09:11 UTC, MasashiYokota commented on src/lib/twitter/accounts.ex
> +    |> Repo.preload(:favorite_posts)
Please explain `Repo.preload` and `preload` of Ecto.Query

2021-02-21 11:41 UTC, ryoheiw commented on src/test/twitter_web/controllers/favorite_controller_test.exs
> +end
Hi Shunji, thank you for the comments. Apology for the long question but: should I be checking if a non-signed in user can access other controllers as well, such as the create, delete and update actions on the post_controller? Right now, the only control flow/restriction to access the favorite_controller and  post_controller actions is being done by A) not showing the link in the view (but can be accessed by the routes directly), and B) by implicitly failing if a lookup to a user fails: I will look up the user in the Plug.Conn struct using `user_id = conn.assigns.current_user.id`. This line fails and result in an `(UndefinedFunctionError)`  because the current_user does not exist within assigns if the user is not logged in and the conde is tantamount to looking up `nil.id()`. I would like this code to be more explicit however, and I think I could either create an `if else` statement within my action like in the photo below, or I can pattern match on the conn struct (even though it will be quite nested) within the function arguments. What would you suggest?
![Screen Shot 2021-02-21 at 8 38 18 PM](https://user-images.githubusercontent.com/45289373/108623897-dd2ab200-7484-11eb-9a75-b03cb57ad754.png)

2021-02-22 02:21 UTC, ryoheiw commented on src/lib/twitter/accounts.ex
> +    |> Repo.preload(:favorite_posts)
In this particular case, because I am only fetching one record using `Repo.get(id)`, `Repo.preload/3` and `Ecto.Query.preload/3` result in the same database query with similar metrics (photo below). However, if I were to use `Repo.all` or create a query using joins, then there is a big difference between `Repo.preload/3` and `Ecto.Query.preload/3` as described below. 


**Ecto.Query.preload/3**
- Use for preloading while you are fetching records
- Only preloads the associations for the records that were left after filtering (can use `join`, `where`): when composing a query for parent and child records in a join query, only one query is run. If you do not do a join, two queries are run, similar to `Repo.preload/3`. 


**Repo.preload/3**
- Use for preloading after you have fetched the record. Results in two queries to the database
- does not load already present associations
- is more limited than `Ecto.Query.preload()` in terms of filtering

![Screen Shot 2021-02-21 at 8 46 40 PM](https://user-images.githubusercontent.com/45289373/108649066-f290f200-74ff-11eb-9c5a-55c7f01b7e36.png)

2021-02-22 02:23 UTC, shunjilin commented on src/test/twitter_web/controllers/favorite_controller_test.exs
> +end
Yes this is pretty tricky,

In our current codebase we test all controllers for authenticated / non authenticated user. Even though this test can be done only for the authenticated plug, we err on the safe side as a developer might forget to `pipe_through` the necessary authentication / validation plugs when creating the controller and adding to the router.ex file.

That being said you might not need to handle sign in redirection for every single controller individually, you can have a catch all redirect method within your auth plug that simply redirects to the sign-in page, that way you only handle the happy path in your controllers.

Hope that answers the question, but please feel free to ask if it is not clear!

2021-02-22 05:45 UTC, MasashiYokota requested changes

2021-02-22 05:45 UTC, MasashiYokota commented on src/lib/twitter_web/views/page_view.ex
> +  @spec liked?(list(Twitter.Tweets.FavoritePosts.t()) | [], Twitter.Tweets.Post.t()) ::
you should add `alias Twitter.Tweets.FavoritePosts` on the top of this module and fix this like below:
```suggestion
  @spec liked?(list(FavoritePosts.t()), Twitter.Tweets.Post.t()) ::
```

By the way, `list` type includes empty list type. So, you shouldn't add `| []`.

2021-02-22 05:51 UTC, shunjilin reviewed
Looks good overall! just one nitpick

2021-02-22 05:51 UTC, shunjilin commented on src/lib/twitter/tweets.ex
> +    |> Repo.get_by!(post_id: post_id, user_id: user_id)
You can probably use where here instead of get_by!, no need to retrieve from database

2021-02-22 05:54 UTC, ryoheiw commented on src/lib/twitter_web/views/page_view.ex
> +  @spec liked?(list(Twitter.Tweets.FavoritePosts.t()) | [], Twitter.Tweets.Post.t()) ::
Thank you for the comment. Does this apply to other structures within this module and for other modules as well? For example, should I add `alias Twitter.Tweets.Post` in this module and write `liked?(list(FavoritePosts.t()), Post.t())` in the spec instead?

2021-02-22 06:45 UTC, shunjilin commented on src/lib/twitter_web/views/page_view.ex
> +  @spec liked?(list(Twitter.Tweets.FavoritePosts.t()) | [], Twitter.Tweets.Post.t()) ::
I think it is a good idea to keep it DRY as much as possible, and if there are conflicts, you can always rename the alias using `as` syntax, e.g. `alias Twitter.Tweets.FavoritePosts as MostFavoritePosts'

2021-02-22 06:47 UTC, shunjilin commented
LGTM

2021-02-22 06:55 UTC, MasashiYokota commented
LGTM

2021-02-22 08:19 UTC, merged