Vue Components and Tests, Backend API
ryoheiw/twitter-clone pull request #4
Opened 2021-03-05 08:57 UTC by ryoheiw

-Changed the backend implementation to create api routes + controllers. 
-Changed the frontend implementation from eex templates ssr to vue components ssr
-Created Vue Components and Vue Tests using jest/vue test utils.

-Remaining: Like Function.お気に入りの機能。

2021-03-05 10:23 UTC, shunjilin requested changes
Minor comments! Overall looks well written and very easy to parse.

One suggestion will be for the test name to be a bit more descriptive, e.g.
```
it("should log in user when form is filled and log in button is clicked")
// instead of
it("login method")
```
That is the purpose of the `it` prefix!

2021-03-05 10:23 UTC, shunjilin commented on src/assets/js/tests/Home.test.js
> +    await expect(api).toHaveBeenNthCalledWith(
cool! I didn't know you can do that! I guess if you don't use await it doesnt resolve?

Looking at my own code I guess I have been cheating by returning an object instead of Promise.resolve() in the mock, your way is more faithful to the interface

2021-03-05 10:23 UTC, shunjilin commented on src/assets/js/tests/Home.test.js
> +          inputUpdate: [, , , "hello2"],
wow, you can do this in JS? does this mean just having the first 3 parameters be undefined?

2021-03-05 10:23 UTC, shunjilin commented on src/assets/js/tests/Home.test.js
> +    wrapper.find(".update").trigger("submit.prevent");
I guess this doesn't work if you just use submit? Interesting, if that is the case!

2021-03-05 10:23 UTC, shunjilin commented on src/assets/js/tests/MenuBar.test.js
> +  test("snapshot matches", () => {
just for consistency may be better to stick to `it` since everywhere else you are using `it`

2021-03-05 10:23 UTC, shunjilin commented on src/assets/js/tests/MenuBar.test.js
> +  });
minor style guide but preferably leave a space between `it` blocks for readibility

2021-03-05 10:23 UTC, shunjilin commented on src/assets/webpack.config.js
> +	const devMode = options.mode !== "production";
maybe reduce the indentation in this file too

2021-03-05 10:23 UTC, shunjilin commented on src/lib/twitter/tweets.ex
> +  @spec create_tweet(%{content: any(), current_user: User.t()}) ::
you might have to update the typespec to take in `id: any()` too

2021-03-05 10:23 UTC, shunjilin commented on src/lib/twitter_web/views/api/post_view.ex
> +  def render(_, _) do
is this catch_all necessary? why not let it fail

2021-03-05 10:23 UTC, shunjilin commented on src/lib/twitter_web/views/api/session_view.ex
> +  def render(_, _) do
same here

2021-03-05 10:23 UTC, shunjilin commented on src/lib/twitter_web/views/api/session_view.ex
> +      logged_in: true
will this ever be false? if not this field may not be necessary?

2021-03-05 10:23 UTC, shunjilin commented on src/lib/twitter_web/views/api/user_view.ex
> +  def render(_, _) do
same here

2021-03-05 10:23 UTC, shunjilin commented on src/test/twitter_web/controllers/api/post_controller_test.exs
> +        conn
for single function calls, preferable to just use the regular function form instead of pipe
same for the rest of this file

2021-03-05 10:23 UTC, shunjilin commented on src/assets/js/components/Home.vue
> +      let params = {
just a style guide, prefer using cost for variables that are not reassigned,
I believe we use the following in our codebase:
https://eslint.org/docs/2.0.0/rules/prefer-const

2021-03-05 12:59 UTC, ryoheiw commented on src/assets/js/tests/Home.test.js
> +          inputUpdate: [, , , "hello2"],
Yes! I guess the equivalent would be something like: 
```
let inputUpdate = new Array(4)
inputUpdate[3] = "hello2"
```

2021-03-07 05:46 UTC, ryoheiw commented on src/lib/twitter_web/views/api/session_view.ex
> +      logged_in: true
Within this current PR, logged in will never be false since if the session authentication fails, an empty map gets returned and the window.location.href will go to the login screen. I use the `logged_in: true` key-value to show or hide the logout button within the `MenuBar.vue`. I pass these values down as props from `Home.vue` to `MenuBar.vue`.  Perhaps I can achieve the same thing with v-if and v-else and do a check on the username, although it will not be as explicit within the menu bar vue component compared to `v-show="logged_in"`. The revised code is below. 

```

<div v-if="username">
    <button class="logout" v-show="logged_in" v-on:click="logout(id)">
      Logout
    </button>
  </div>
  <div v-else>
    <button class="register" v-on:click="register">
      Register
    </button>
    <button class="login" v-on:click="login">Login</button>
  </div>
  
  ```

2021-03-08 01:55 UTC, ryoheiw commented on src/assets/js/tests/Home.test.js
> +    await expect(api).toHaveBeenNthCalledWith(
I have tried this without await and the tests pass so the await is redundant. Will remove.

2021-03-08 02:25 UTC, shunjilin commented on src/lib/twitter_web/views/api/session_view.ex
> +      logged_in: true
The refactor looks good! For the `logged_in` field, if there is a logged in: true field with status success, there should probably also be a logged in: false field with status success (probably with all the other fields null). If you are returning a failure response when logged in is not true, then you can decide your control flow on the status code and the logged_in: true is probably redundant

2021-03-08 02:25 UTC, shunjilin commented
The refactor looks good! Just one reply on the logged_in field

2021-03-08 02:33 UTC, ryoheiw commented on src/lib/twitter_web/views/api/session_view.ex
> +      logged_in: true
Got it.

2021-03-08 03:18 UTC, MasashiYokota commented on src/lib/twitter_web/controllers/api/post_controller.ex
> +    |> put_status(:ok)
When you want to put some error status to response, you should use `put_status`.
It's too much. Please remove this(please fix other actions and controllers, too)

2021-03-08 03:25 UTC, MasashiYokota requested changes
I've commented.

2021-03-08 03:25 UTC, MasashiYokota commented on src/lib/twitter_web/views/api/post_view.ex
> +  end
You shouldn't return empty map. If you are me, I return `%{message: "success"}` because it's easier to handle a response in frontend. (Please fix other View modules, too)

2021-03-08 03:25 UTC, MasashiYokota commented on src/assets/js/components/Home.vue
> +      custom_fetch("patch", `/api/posts/${id}`, params);
Don't redirect after you post, update, or delete a tweet. Instead, please update vue's state.

2021-03-09 02:41 UTC, shunjilin requested changes
Just some minor comments, looks good otherwise!

2021-03-09 02:41 UTC, shunjilin commented on src/assets/js/tests/NewUser.test.js
> +describe.only("NewUser.vue", () => {
maybe remove the `only` tags

2021-03-09 02:41 UTC, shunjilin commented on src/assets/js/tests/NewSession.test.js
> +
this is ok!
another alternative to using done and handling async methods is to use await syntax,
e.g.
```
await wrapper.vm.$nextTick()
expect(api).toHaveBeenCalledWith ...
```
this way you might not have to use done

2021-03-09 02:41 UTC, shunjilin commented on src/assets/js/axios_requests/requests.js
> +async function custom_fetch(action, url, params = {}) {
since you have a default parameter for your custom_fetch, you can remove the last argument for some of the client's that call this function, e.g. delete

2021-03-09 02:59 UTC, shunjilin commented on src/assets/js/components/Home.vue
> +    const response = await custom_fetch("get", "/api/sessions", {});
redundant third argument!

2021-03-09 03:09 UTC, shunjilin approved these changes
LGTM

2021-03-09 03:17 UTC, MasashiYokota commented
LGTM 👍 Please tackle the next task!

2021-03-09 03:23 UTC, merged