Vue like function
ryoheiw/twitter-clone pull request #5
Opened 2021-03-09 06:05 UTC by ryoheiw

-like and unlike functionality and testing

2021-03-09 06:45 UTC, shunjilin requested changes
some nitpicks!

2021-03-09 06:45 UTC, shunjilin commented on src/assets/js/tests/Home.test.js
> +  test("like button calls like method & calls customs fetch", async () => {
nitpick, `it`

2021-03-09 06:45 UTC, shunjilin commented on src/lib/twitter_web/views/api/session_view.ex
> +  def render("success_session.json", _) do
we are not too strict on typing the view, but since you have typed the others, maybe just add typespec here for consistency

2021-03-09 06:45 UTC, shunjilin commented on src/test/twitter_web/controllers/api/favorite_controller_test.exs
> +defmodule TwitterWeb.API.FavoriteControllerTest do
may be good to test what should happen if non signed in user tries to use this endpoint

2021-03-09 06:45 UTC, shunjilin commented on src/assets/js/components/Home.vue
> +        this.inputUpdate[id] = "";
im not sure if  you need this to be reactive, but if so you may have to reassign the entire list instead of assign by index (non -reactive)

2021-03-09 07:33 UTC, shunjilin commented on src/test/twitter_web/controllers/api/favorite_controller_test.exs
> +  describe "Not Signed In User: " do
maybe have a plug to catch unauthorized users and return an error

2021-03-09 08:52 UTC, ryoheiw commented on src/assets/js/tests/__snapshots__/Home.test.js.snap
> +exports[`Home.vue matches the snapshot 1`] = `<!---->`;
ok sounds good!

2021-03-09 08:53 UTC, shunjilin approved these changes
Great! LGTM

2021-03-10 02:23 UTC, MasashiYokota commented
LGTM 👍 Good job!

2021-03-11 06:24 UTC, merged